version: '3.1'
services:
  postgresql:
    image: postgres:12.10
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef